[project]
name = "python-labs"
version = "0.1.0"
description = "This project is my python-revision hub."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "scikit-learn>=1.8.0",
    "streamlit>=1.53.0",
]
